### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by ivancesar-tt** [Splitit/Splitit.SDKs#1]
Original (from Assaf, google doc):

> I belive we should return exception from the SDK api instead of responseHeader with error as part of every call.

**Comment by ivancesar-tt** [comment]
You mean to parse response header within SDK library and throw exception?

**Comment by assafbazar** [comment]
yes - i believe that every exceptional behaviour , either due to technial issue or buisness error , should throw  exception with the error code + description within the SDK library to the client so any client that use it will not need to check each time the response for errors (only as part of catch section) . what do you think ?

**Comment by ivancesar-tt** [comment]
OK, sounds good to me!

**Comment by ivancesar-tt** [comment]
On each response where Succeeded = False, exception is thrown.
